server:
  port: 9082
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qing?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    dbcp2:
      min-idle: 20                                           # 数据库连接池的最小维持连接数
      initial-size: 20                                       # 初始化连接数
      max-total: 40                                          # 最大连接数
      max-wait-millis: 60000                                  # 等待连接获取的最大超时时间
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
          ddl-auto: update
  redis: 
     host: 127.0.0.1
     port: 6379
     password: 
     max-active: 8
     max-wait: -1
     max-idle: 8
     min-idle: 0
     timeout: 30000
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations: classpath:mybatis/mapper/**/*.xml
logging:
  config: classpath:logback.xml

  
  
  
